# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: CI=false npm run build --if-present
    - run: npm test

     # ===== 新增：上传构建产物 =====
    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
          # 给这个产物起个名字
          name: react-app-build
          # 指定要上传的文件夹路径，通常是构建输出目录
          path: build/
          # 可选：设置保留天数，默认90天
          retention-days: 30
